In [1]:
import pandas as pd

In [3]:
data = {
    "a":[0,0,1,1,2,2],
    "b":[0,1,2,3,10,20],
    "c":[0,5,6,8,20,40]
}

data = pd.DataFrame(data)
data

   a   b   c
0  0   0   0
1  0   1   5
2  1   2   6
3  1   3   8
4  2  10  20
5  2  20  40

In [12]:
_data = data.groupby("a").mean()
_data

      b     c
a
0   0.5   2.5
1   2.5   7.0
2  15.0  30.0

In [13]:
_data["a"] = _data.index

In [14]:
_data

      b     c  a
a
0   0.5   2.5  0
1   2.5   7.0  1
2  15.0  30.0  2

In [15]:
_data["a"].apply(lambda x:x+1)

a
0    1
1    2
2    3
Name: a, dtype: int64

In [6]:
import pandas as pd
import datetime

QA_FILE_PATH = "test_save.csv"

data = pd.read_csv(QA_FILE_PATH,index_col=0) 
print("data[adm]",pd.to_datetime(data["administration_date"]) > "2025-01-01")

data[adm] 0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
Name: administration_date, dtype: bool